homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  base_url: schalken.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3
  api_password: !secret http_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  # random sensor test
  - platform: random

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Configuring MQTT on Hass.io
# https://community.home-assistant.io/t/configuring-mqtt-on-hass-io/34040
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant-1

# based on example
# https://www.home-assistant.io/components/mysensors/#presentation
mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: 'path/mysensors.json'
      baud_rate: 38400
      nodes:
        1:
          name: 'kitchen'
    - device: '/dev/ttyACM0'
      persistence_file: 'path/mysensors2.json'
      baud_rate: 115200
    - device: '192.168.1.18'
      persistence_file: 'path/mysensors3.json'
      tcp_port: 5003
    - device: mqtt
      persistence_file: 'path/mysensors4.json'
      topic_in_prefix: 'mygateway1-out'
      topic_out_prefix: 'mygateway1-in'
  optimistic: false
  persistence: true
  retain: true
  version: '2.0'

# Side panel
# Add configurator to the side panel
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://schalken.duckdns.org:3218

device_tracker:
  - platform: bluetooth_tracker
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: !secret icloud_descriptive_name

# Pick any icon that you can find on materialdesignicons.com and prefix the name with mdi:
zone:
  - name: Home
    latitude: 51.611157
    longitude: 4.806703
    radius: 100
    icon: mdi:home

  - name: School
    latitude: 51.606920
    longitude: 4.813119
    radius: 50
    icon: mdi:school

  - name: Van Lanschot Den Bosch
    latitude: 51.691235 
    longitude: 5.292575
    radius: 100
    icon: mdi:account-clock

logger:
  default: info
  logs:
    homeassistant.components.mysensors: debug
    mysensors: debug