homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  country: NL
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 85.144.196.197 # my external ip adres
    - type: homeassistant
  time_zone: Europe/Amsterdam

automation: !include yaml/automations.yaml
group: !include yaml/groups.yaml
input_boolean: !include yaml/input_booleans.yaml
input_select: !include yaml/input_selects.yaml
light: !include yaml/lights.yaml
script: !include yaml/scripts.yaml
sensor: !include yaml/sensors.yaml
switch: !include yaml/switches.yaml
timer: !include yaml/timer.yaml

mqtt: !include yaml/mqtt.yaml

# enable system health monitoring
# https://www.home-assistant.io/integrations/system_health/
system_health:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Pick any icon that you can find on http://materialdesignicons.com/ and prefix the name with mdi:
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home

  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 50
    icon: mdi:school

  - name: Werk Jeroen Den Bosch
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 100
    icon: mdi:account-clock

  - name: Werk Jeroen Amsterdam
    latitude: !secret work_amsterdam_latitude
    longitude: !secret work_amsterdam_longitude
    radius: 100
    icon: mdi:account-clock

# Track the sun
sun:

# The Mobile App integration allows Home Assistant mobile apps to easily integrate with Home Assistant.
# https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

api:

recorder:
  purge_keep_days: 1
  commit_interval: 60
  exclude:
    domains:
      - automation
      - camera
      - input_text
      - sun
      - water_heater
      - weather
      - weblink
      - updater
      - zone

# Text to speech
tts:
  - platform: google_translate

# enable mqtt logging
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.recorder.migration: info
    homeassistant.components.automation: debug
    homeassistant.components.script: debug
