homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include yaml/customize.yaml

# Show links to resources in log and frontend; disable to hide
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://schalken.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3
  api_password: !secret http_password # legacy_api_password support has been enabled. If you don't require it, remove the 'api_password' from your http config.
  

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Pick any icon that you can find on materialdesignicons.com and prefix the name with mdi:
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home

  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 50
    icon: mdi:school

  - name: Van Lanschot Den Bosch
    latitude: 51.691235 
    longitude: 5.292575
    radius: 100
    icon: mdi:account-clock

# Track the sun
sun:

weather:
  - platform: buienradar
    name: buienradar1
    entity: brw
    forecast: True

weather:
  - platform: darksky
    name: darksky
    api_key: !secret darksky_API_KEY
    mode: daily # The forecast type. Can be hourly or daily. Default value: hourly


sensor: !include yaml/sensors.yaml


# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# MQTT Broker configuration
# REF: https://www.home-assistant.io/docs/mqtt/broker/#run-your-own
mqtt: !include yaml/mqtt.yaml
  
mysensors: !include yaml/mysensors.yaml

group: !include yaml/groups.yaml
automation: !include yaml/automations.yaml
script: !include yaml/scripts.yaml
