resources:
  - url: /local/simple-thermostat/simple-thermostat.js?v=2
    type: module
  - url: /local/content-card-example.js
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module
  - url: /local/lightslider/lightslider.js?v=0.1.1
    type: module
  - url: /local/heat-controler/heat-controler.js?v=0.1.1
    type: module

# custom_updater:
#   card_urls:
#     - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/allow-updates/tracker.json
views:
  - title: Woonkamer
    icon: mdi:home
    path: default_view
    badges: 
      - device_tracker.jeroensipad
      - device_tracker.iphonevanjeroen
      - device_tracker.iphone_van_jeroen
    cards: 
      - type: media-control
        entity: media_player.woonkamer
      - type: entities
        title: Woonkamper lampen
        show_header_toggle: false
        entities:
          - entity: light.woonkamer_lampen
          - entity: light.bollamp
          - entity: light.eettafel
          - switchEntity: light.eettafel
            type: custom:light-slider
          - entity: light.led_lamp_4_bureau
views:
  - title: Heat Controler
    icon: mdi:fire
    cards: 
      - type: entities
        title: Heating Controler
        entities:
          - entity: sensor.floor_downstairs_main_in
          - entity: sensor.floor_downstairs_main_out
          - entity: sensor.floor_downstairs_1_in
          - entity: sensor.floor_downstairs_1_out
          - entity: sensor.floor_downstairs_2_in
          - entity: sensor.floor_downstairs_2_out
          - entity: sensor.floor_downstairs_3_in
          - entity: sensor.floor_downstairs_3_out
          - entity: sensor.floor_downstairs_4_in
          - entity: sensor.floor_downstairs_4_out
          - entity: sensor.floor_downstairs_5_in
          - entity: sensor.floor_downstairs_5_out
          - entity: sensor.floor_downstairs_6_in
          - entity: sensor.floor_downstairs_6_out
          - entity: sensor.floor_downstairs_7_in
          - entity: sensor.floor_downstairs_7_out
      - title: Downstairs heat controller
        type: custom:heat-controler
        entity: sensor.floor_downstairs_main_in

