- alias: WC1 - Turn on light on door open or motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.wc_movement_konke_155f07fe_ias_zone
      to: "on"
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_064cdd01_on_off
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_clear_250lm_af3d25fe_level_on_off
- alias: WC1 - Turn off light after 1 minute if no motion and door closes
  trigger:
    - platform: state
      entity_id: binary_sensor.wc_movement_konke_155f07fe_ias_zone
      to: "off"
      for:
        minutes: 3
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_064cdd01_on_off
      to: "off"
      for:
        seconds: 10
  condition:
    - condition: state
      entity_id: binary_sensor.wc_movement_konke_155f07fe_ias_zone
      state: "off"
      for:
        seconds: 10
  action:
    - service: light.turn_off
      entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_clear_250lm_af3d25fe_level_on_off

- alias: Power state on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: sonoffs/cmnd/state
        payload: ""
  id: 50fad415012446deba4dfbf4ee32815d
- id: login_failure
  alias: Login Failure
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown'
      }}"
  action:
    service: notify.ios_your_iphone
    data:
      message: Warning - Failed login attempt detected.
- id: "1613074545149"
  alias: WC1 - Yet Another Motion Automation
  description: ""
  use_blueprint:
    path: networkingcat/yet_another_motion_automation.yaml
    input:
      no_motion_wait: "120"
      motion_entity: group.wc_motion
      light_target:
        entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_clear_250lm_af3d25fe_level_on_off
      time_scene_night: 0:00:00
      time_scene_evening: 0:00:00
- id: "1613503640920"
  alias: Door magnet and motion
  description: ""
  use_blueprint:
    path: schalken/door-magnet-and-motion.yaml
    input:
      door_sensor: binary_sensor.test_lumi_magnet_on_off
      motion_sensor: binary_sensor.lumi_sensor_motion_1_zone
      light: light.test_ikea_e27_806lm
      wait-for-movement-duration: "6"
      duration: "31"
- id: "1613726721789"
  alias: "Jeroen - bed lamp switch "
  description: ZHA - Aqara Wireless Mini Switch
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      button_single_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_1
          domain: switch
      button_double_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_2
          domain: switch
      button_long_press:
        - service: homeassistant.turn_off
          data: {}
          entity_id: group.master_lights
      aqara_mini_switch: 4d0dad1a8c5f81044113007ab77d8792
- id: "1626414640595"
  alias: Bureaulicht Jeroen aan
  description: ""
  trigger:
    - device_id: 45ec225df75053dccc34ee69d97868fd
      domain: zha
      platform: device
      type: remote_button_short_press
      subtype: remote_button_short_press
  condition: []
  action:
    - type: toggle
      device_id: 8271b699a77443cdb3d2a4b3010d299b
      entity_id: switch.tasmota_24_1
      domain: switch
  mode: single
- id: "1626459470208"
  alias: "Maria - bed lamp switch "
  description: ZHA - Aqara Wireless Mini Switch
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      aqara_mini_switch: 789b9f5bc25ea05544feaa15cb9165a8
      button_single_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_2
          domain: switch
      button_double_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_1
          domain: switch
      button_long_press: []
- id: "1627458339900"
  alias: "Ikea 5-remote "
  description: Woonkamer
  use_blueprint:
    path: niro1987/zha_ikea_tradfri_5button_remote_custom.yaml
    input:
      remote: 4e3a251021e3bf8ef6bd97679dff815a
      power_short:
        - service: homeassistant.toggle
          target:
            device_id: ed8f64d88a667f81b7b52de6c3e19c14
      power_long:
        - service: light.toggle
          target:
            entity_id: light.eettafel
      dimup_short:
        - device_id: ed8f64d88a667f81b7b52de6c3e19c14
          domain: light
          entity_id: light.bollamp_new
          type: brightness_increase
      dimdown_short:
        - device_id: ed8f64d88a667f81b7b52de6c3e19c14
          domain: light
          entity_id: light.bollamp_new
          type: brightness_decrease
      colorup_short:
        - device_id: 2772d123b3f2942e924ce87e5367fdb7
          domain: light
          entity_id: light.tafel_1_new
          type: brightness_increase
        - device_id: 0f2258249aa9cd44d07a0f973705ac26
          domain: light
          entity_id: light.tafel_2_new
          type: brightness_increase
      colordown_short:
        - device_id: 2772d123b3f2942e924ce87e5367fdb7
          domain: light
          entity_id: light.tafel_1_new
          type: brightness_decrease
        - device_id: 0f2258249aa9cd44d07a0f973705ac26
          domain: light
          entity_id: light.tafel_2_new
          type: brightness_decrease
- id: "1635954827756"
  alias: Bureau Jeroen mini
  description: ""
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      aqara_mini_switch: 45ec225df75053dccc34ee69d97868fd
      button_single_press:
        - type: toggle
          device_id: 8271b699a77443cdb3d2a4b3010d299b
          entity_id: switch.tasmota_24_1
          domain: switch
      button_double_press:
        - type: toggle
          device_id: 8271b699a77443cdb3d2a4b3010d299b
          entity_id: switch.tasmota_24_2
          domain: switch
      button_long_press:
        - type: toggle
          device_id: 8271b699a77443cdb3d2a4b3010d299b
          entity_id: switch.tasmota_24_3
          domain: switch
