- id: "1727515368938"
  alias: Aanrecht
  description: ""
  use_blueprint:
    path: schalken/double_switch.yaml
    input:
      switch_1: switch.tasmota_1_2
      switch_2: switch.tasmota_17_1

- id: "1727515368939"
  alias: Keukentafel
  description: ""
  use_blueprint:
    path: schalken/double_switch.yaml
    input:
      switch_1: switch.tasmota_1_1
      switch_2: switch.tasmota_17_2

############################################################################################################
# Begane grond
#

# Wc1 light automation
- alias: "WC 1 Light On When Open WC Door"
  trigger:
    - platform: state
      entity_id: input_select.wc1_status
      to: "open"
  action:
    - service: light.turn_on
      target:
        entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_clear_250lm_af3d25fe_level_on_off

- alias: "WC 1 Light On When Open WC Door"
  trigger:
    - platform: state
      entity_id: input_select.wc1_status
      to: "in"
  action:
    - service: light.turn_on
      target:
        entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_clear_250lm_af3d25fe_level_on_off

- alias: "WC 1 Light Off When going Out the WC"
  trigger:
    - platform: state
      entity_id: input_select.wc1_status
      to: "out"
  action:
    - service: light.turn_off
      target:
        entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_clear_250lm_af3d25fe_level_on_off

# Wc1 state automation
- alias: "Set WC 1 Status to Open on Door Open"
  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_064cdd01_on_off
      to: "on"
  condition:
    - condition: state
      entity_id: input_select.wc1_status
      state: "out"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "open"

- alias: "Set WC 1 Status to In on Movement"
  trigger:
    - platform: state
      entity_id: binary_sensor.wc_movement_konke_155f07fe_ias_zone
      to: "on"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "in"

- alias: "Set WC 1 Status to Out on Door Closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_064cdd01_on_off
      to: "off"
  condition:
    - condition: state
      entity_id: input_select.wc1_status
      state: "open"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "out"

- alias: "Set WC 1 Status to Out on Door Closed When In"
  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_064cdd01_on_off
      to: "off"
  condition:
    - condition: state
      entity_id: input_select.wc1_status
      state: "in"
      for:
        seconds: 10
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "out"

- alias: "Set WC 1 Status to In on Movement When Out"
  trigger:
    - platform: state
      entity_id: binary_sensor.wc_movement_konke_155f07fe_ias_zone
      to: "on"
  condition:
    - condition: state
      entity_id: input_select.wc1_status
      state: "out"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "in"

- alias: "WC 1 Status to In on Door Open with Motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_064cdd01_on_off
      to: "on"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_select.wc1_status
          state: "out"
        - condition: state
          entity_id: binary_sensor.wc_movement_konke_155f07fe_ias_zone
          state: "on"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "in"

# Wc1 timer automation
- alias: "Start WC 1 Timer on Open"
  trigger:
    - platform: state
      entity_id: input_select.wc1_status
      to: "open"
  action:
    - service: timer.start
      target:
        entity_id: timer.wc1_status_timer

- alias: "Start WC 1 Timer on In"
  trigger:
    - platform: state
      entity_id: input_select.wc1_status
      to: "in"
  action:
    - service: timer.start
      target:
        entity_id: timer.wc1_status_timer

- alias: "Set WC 1 Status to Out After Timer"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wc1_status_timer
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.wc1_status
      data:
        option: "out"

############################################################################################################
# Other configuuration
#

- alias: Power state on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: sonoffs/cmnd/state
        payload: ""
  id: 50fad415012446deba4dfbf4ee32815d
- id: login_failure
  alias: Login Failure
  trigger:
    platform: template
    value_template: "{{ states('persistent_notification.httplogin') != 'unknown'
      }}"
  action:
    service: notify.ios_your_iphone
    data:
      message: Warning - Failed login attempt detected.

############################################################################################################
# Zolder
#

- id: "1613726721789"
  alias: "Jeroen - bed lamp switch "
  description: ZHA - Aqara Wireless Mini Switch
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      button_single_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_1
          domain: switch
      button_double_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_2
          domain: switch
      button_long_press:
        - service: homeassistant.turn_off
          data: {}
          entity_id: group.master_lights
      aqara_mini_switch: 4d0dad1a8c5f81044113007ab77d8792

- id: "1626459470208"
  alias: "Maria - bed lamp switch "
  description: ZHA - Aqara Wireless Mini Switch
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      aqara_mini_switch: 789b9f5bc25ea05544feaa15cb9165a8
      button_single_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_2
          domain: switch
      button_double_press:
        - type: toggle
          device_id: ad2b2d4df76c4fc3ba2ba3902e20cbdf
          entity_id: switch.tasmota_3_1
          domain: switch
      button_long_press: []

############################################################################################################
# Kantoor
#

- id: "1635954827756"
  alias: Bureau Jeroen mini
  description: ""
  use_blueprint:
    path: SeanM/zha-aqara-wireless-mini-switch.yaml
    input:
      aqara_mini_switch: 45ec225df75053dccc34ee69d97868fd
      button_single_press:
        - type: toggle
          device_id: 8271b699a77443cdb3d2a4b3010d299b
          entity_id: switch.tasmota_24_1
          domain: switch
      button_double_press:
        - type: toggle
          device_id: 8271b699a77443cdb3d2a4b3010d299b
          entity_id: switch.tasmota_24_2
          domain: switch
      button_long_press:
        - type: toggle
          device_id: 8271b699a77443cdb3d2a4b3010d299b
          entity_id: switch.tasmota_24_3
          domain: switch

# - id: "1626414640595"
#   alias: Bureaulicht Jeroen aan
#   description: ""
#   trigger:
#     - device_id: 45ec225df75053dccc34ee69d97868fd
#       domain: zha
#       platform: device
#       type: remote_button_short_press
#       subtype: remote_button_short_press
#   condition: []
#   action:
#     - type: toggle
#       device_id: 8271b699a77443cdb3d2a4b3010d299b
#       entity_id: switch.tasmota_24_1
#       domain: switch
#   mode: single

############################################################################################################
# Woonkamer
#

# bollamp
- alias: "Turn on Bollamp when Tasmota switch is on"
  trigger:
    - platform: state
      entity_id: switch.tasmota_2_3
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.bollamp_new

- alias: "Turn off Bollamp when Tasmota switch is off"
  trigger:
    - platform: state
      entity_id: switch.tasmota_2_3
      to: "off"
  action:
    - service: light.turn_off
      entity_id: light.bollamp_new

# Eettafel
- alias: "Turn on Tafel lights when Tasmota switch is on"
  trigger:
    - platform: state
      entity_id: switch.tasmota_2_2
      to: "on"
  action:
    - service: light.turn_on
      entity_id:
        - light.tafel_1_new
        - light.tafel_2_new_2

- alias: "Turn off Tafel lights when Tasmota switch is off"
  trigger:
    - platform: state
      entity_id: switch.tasmota_2_2
      to: "off"
  action:
    - service: light.turn_off
      entity_id:
        - light.tafel_1_new
        - light.tafel_2_new_2

- id: "1627458339900"
  alias: "Ikea 5-remote "
  description: Woonkamer
  use_blueprint:
    path: niro1987/zha_ikea_tradfri_5button_remote_custom.yaml
    input:
      remote: 4e3a251021e3bf8ef6bd97679dff815a
      power_short:
        - service: homeassistant.toggle
          target:
            device_id: ed8f64d88a667f81b7b52de6c3e19c14
      power_long:
        - service: light.toggle
          target:
            entity_id: light.eettafel
      dimup_short:
        - device_id: ed8f64d88a667f81b7b52de6c3e19c14
          domain: light
          entity_id: light.bollamp_new
          type: brightness_increase
      dimdown_short:
        - device_id: ed8f64d88a667f81b7b52de6c3e19c14
          domain: light
          entity_id: light.bollamp_new
          type: brightness_decrease
      colorup_short:
        - device_id: 2772d123b3f2942e924ce87e5367fdb7
          domain: light
          entity_id: light.tafel_1_new
          type: brightness_increase
        - device_id: 0f2258249aa9cd44d07a0f973705ac26
          domain: light
          entity_id: light.tafel_2_new
          type: brightness_increase
      colordown_short:
        - device_id: 2772d123b3f2942e924ce87e5367fdb7
          domain: light
          entity_id: light.tafel_1_new
          type: brightness_decrease
        - device_id: 0f2258249aa9cd44d07a0f973705ac26
          domain: light
          entity_id: light.tafel_2_new
          type: brightness_decrease
