blueprint:
  name: Door magnet and motion
  description: Switch the light of a room, quickly and short, on door open long on movement switch quickly off when leaving the room
  domain: automation
  input:
    door_sensor:
      name: Door sensor
      description: A sensor that detects opening and closing of the door (preferable a magnet sensor)
      selector:
        entity:
          domain: binary_sensor
    motion_sensor:
      name: Motion sensor
      description: A sensor that detects motion
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light:
      name: Light
      description: A light that is turned on and off
      selector:
        entity:
          domain: light
    duration:
      name: Duration
      description: How long the light should stay on for, after motion is detected,
        before turning off (defaults to 30 seconds)
      default: 30
      selector:
        number:
          min: 0
          max: 300
          mode: slider
    wait-for-movement-duration:
      name: Wait for movement duration
      description: How long the light stays on after door close, without any movement
      default: 5
      selector:
        number:
          min: 0
          max: 300
          mode: slider  
trigger:
- entity_id: !input 'door_sensor'
  platform: state
  to: 'off'
- entity_id: !input 'door_sensor'
  platform: state
  to: 'on'
- entity_id: !input 'motion_sensor'
  platform: state
  to: 'off'
- entity_id: !input 'motion_sensor'
  platform: state
  to: 'on'

variables:
  motion: !input 'motion_sensor' 
  door: !input 'door_sensor'
  light: !input 'light'
  doormode: '{{ states(door) }}'
  motionmode: '{{ states(motion) }}'

action:
- choose:
  - conditions: "{{ is_state(door, 'on') }}" # long click
    sequence: 
    - data:
        entity_id: '{{light}}'
      service: light.turn_on
    - wait_template: "{{ is_state(door, 'off') }}"
      timeout: !input wait-for-movement-duration
      continue_on_timeout: true
  default:
  - data:
      entity_id: '{{light}}'
    service: light.turn_off

mode: single


# https://community.home-assistant.io/t/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor/255902


