# # REF: https://www.home-assistant.io/docs/mqtt/broker/#run-your-own
# # MQTT Broker configuration
# # REF: https://www.home-assistant.io/docs/mqtt/broker/#run-your-own
# # based on https://github.com/brahmafear/hass_config/blob/master/yaml/mqtt.yaml
# # stripped to: https://forum.mysensors.org/topic/5832/struggling-with-configure-yaml/21
# broker: 192.168.1.18 # The IP address or hostname of your MQTT broker, e.g., 192.168.1.32.
# port: 1883 # The network port to connect to. Default is 1883.
# # client_id: home-assistant # The client ID that Home Assistant will use. Has to be unique on the server. Default is a randomly generated one.
# keepalive: 60 # The time in seconds between sending keep alive messages for this client. Default is 60.
sensor:
  - name: "2 temperature"
    state_topic: "mysensors-out/2/11/#"

  - name: "2 humidity"
    state_topic: "mysensors-out/2/10/#"

  - name: "3 temperature"
    state_topic: "mysensors-out/3/11/#"

  - name: "3 humidity"
    state_topic: "mysensors-out/3/10/#"

  - name: "3 heater"
    state_topic: "mysensors-in/3/12"

  - name: "4 temperature"
    state_topic: "mysensors-out/4/11/#"

  - name: "4 humidity"
    state_topic: "mysensors-out/4/10/#"

  - name: "5 temperature"
    state_topic: "mysensors-out/5/11/#"

  - name: "5 humidity"
    state_topic: "mysensors-out/5/10/#"
  # floor heater downstairs

  - name: "floor downstairs 1 in"
    state_topic: "mysensors-out/7/13/1/0/0"

  - name: "floor downstairs 1 out"
    state_topic: "mysensors-out/7/10/1/0/0"

  - name: "floor downstairs 2 in"
    state_topic: "mysensors-out/7/4/1/0/0"

  - name: "floor downstairs 2 out"
    state_topic: "mysensors-out/7/3/1/0/0"

  - name: "floor downstairs 3 in"
    state_topic: "mysensors-out/7/14/1/0/0"

  - name: "floor downstairs 3 out"
    state_topic: "mysensors-out/7/0/1/0/0"

  - name: "floor downstairs 4 in"
    state_topic: "mysensors-out/7/11/1/0/0"

  - name: "floor downstairs 4 out"
    state_topic: "mysensors-out/7/5/1/0/0"

  - name: "floor downstairs 5 in"
    state_topic: "mysensors-out/7/8/1/0/0"

  - name: "floor downstairs 5 out"
    state_topic: "mysensors-out/7/7/1/0/0"

  - name: "floor downstairs 6 in"
    state_topic: "mysensors-out/7/6/1/0/0"

  - name: "floor downstairs 6 out"
    state_topic: "mysensors-out/7/9/1/0/0"

  - name: "floor downstairs 7 in"
    state_topic: "mysensors-out/7/16/1/0/0"

  - name: "floor downstairs 7 out"
    state_topic: "mysensors-out/7/12/1/0/0"

  - name: "floor downstairs main in"
    state_topic: "mysensors-out/7/15/1/0/0"

  - name: "floor downstairs main out"
    state_topic: "mysensors-out/7/2/1/0/0"

  - name: "floor downstairs environment"
    state_topic: "mysensors-out/7/2/1/0/0"
# floor heater upstairs

